FROM docker.io/library/alpine:3.22.0
ARG HUGO_VERSION

# Install necessary packages
RUN apk update \
    && rm -rf /var/cache/apk/*

# Download Hugo from github
RUN mkdir -p /opt/hugo \
    && cd /opt/hugo \
    && wget -O hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.tar.gz" \
    && tar -xvzf hugo.tar.gz \
    && rm hugo.tar.gz

# Create and use a non-root user account
RUN addgroup -g 1000 appgroup \
    && adduser -G appgroup -u 1000 -D appuser

ENV PATH="/opt/hugo:${PATH}"

USER appuser
