FROM docker.io/library/alpine:3.22.0

# Install necessary packages
RUN apk update \
    && apk add --no-cache ffmpeg \
    && apk add --no-cache yt-dlp-core \
    && rm -rf /var/cache/apk/*

# Create and use a non-root user account
RUN addgroup -g 1000 appgroup \
    && adduser -G appgroup -u 1000 -D appuser
USER appuser

ENTRYPOINT ["yt-dlp"]
