FROM alpine:latest

# Install necessary packages
RUN apk update \
    && apk add --no-cache plantuml \
    && rm -rf /var/cache/apk/*

# Create and use a non-root user account
RUN addgroup -g 1000 appgroup \
    && adduser -G appgroup -u 1000 -D appuser
USER appuser

ENTRYPOINT ["plantuml"]
